;;; conductor.lisp — Prompt orchestration entry points.

(in-package :harmonia)

(defun %extract-tag-value (prompt tag)
  (let* ((needle (format nil "~A=" tag))
         (start (search needle prompt :test #'char-equal)))
    (when start
      (let* ((from (+ start (length needle)))
             (space (position #\Space prompt :start from)))
        (subseq prompt from (or space (length prompt)))))))

(defun %split-by-comma (text)
  (let ((parts '())
        (start 0))
    (loop for i = (position #\, text :start start)
          do (push (string-trim '(#\Space #\Tab) (subseq text start (or i (length text)))) parts)
          if (null i) do (return)
          do (setf start (1+ i)))
    (remove-if (lambda (s) (zerop (length s))) (nreverse parts))))

(defun %clip-text (text &optional (limit 512))
  (let ((s (or text "")))
    (if (<= (length s) limit)
        s
        (subseq s 0 limit))))

(defun %maybe-handle-self-push-test (prompt)
  (when (search "self-push-test" prompt :test #'char-equal)
    (let* ((repo (%extract-tag-value prompt "repo"))
           (branch (%extract-tag-value prompt "branch")))
      (unless (and repo branch)
        (error "self-push-test requires repo=<path> and branch=<name>"))
      (with-open-file (out (merge-pathnames "SELF_PUSH_TEST_FROM_HARMONIA.txt" repo)
                           :direction :output :if-exists :supersede :if-does-not-exist :create)
        (format out "self-push by harmonia at ~A~%" (get-universal-time)))
      (git-commit-and-push repo branch "self push test from harmonia loop")
      (format nil "SELF_PUSH_OK repo=~A branch=~A" repo branch))))

(defun %maybe-handle-tool-command (prompt)
  (when (search "tool " prompt :test #'char-equal)
    (let ((op (%extract-tag-value prompt "op")))
      (unless op
        (error "tool command requires op=<name>"))
      (cond
        ((string-equal op "whatsapp-store-device")
         (harmonic-matrix-route-or-error "orchestrator" "whatsapp")
         (let ((device (%extract-tag-value prompt "device"))
               (creds (%extract-tag-value prompt "creds")))
           (unless (and device creds) (error "whatsapp-store-device requires device=<id> creds=<token>"))
           (whatsapp-store-linked-device device creds)
           (values "WHATSAPP_DEVICE_STORED" "whatsapp")))
        ((string-equal op "whatsapp-send")
         (harmonic-matrix-route-or-error "orchestrator" "whatsapp")
         (values (whatsapp-send-text (or (%extract-tag-value prompt "to") "")
                                     (or (%extract-tag-value prompt "text") ""))
                 "whatsapp"))
        ((string-equal op "telegram-send")
         (harmonic-matrix-route-or-error "orchestrator" "telegram")
         (values (telegram-send-text (or (%extract-tag-value prompt "chat") "")
                                     (or (%extract-tag-value prompt "text") ""))
                 "telegram"))
        ((string-equal op "slack-send")
         (harmonic-matrix-route-or-error "orchestrator" "slack")
         (values (slack-send-text (or (%extract-tag-value prompt "channel") "")
                                  (or (%extract-tag-value prompt "text") ""))
                 "slack"))
        ((string-equal op "mattermost-send")
         (harmonic-matrix-route-or-error "orchestrator" "mattermost")
         (values (mattermost-send-text (or (%extract-tag-value prompt "channel") "")
                                       (or (%extract-tag-value prompt "text") ""))
                 "mattermost"))
        ((string-equal op "nostr-publish")
         (harmonic-matrix-route-or-error "orchestrator" "nostr")
         (values (nostr-publish-text (or (%extract-tag-value prompt "text") ""))
                 "nostr"))
        ((string-equal op "email-send")
         (harmonic-matrix-route-or-error "orchestrator" "email-client")
         (values (email-send (or (%extract-tag-value prompt "to") "")
                             (or (%extract-tag-value prompt "subject") "")
                             (or (%extract-tag-value prompt "body") ""))
                 "email-client"))
        ((string-equal op "search")
         (values (search-web (or (%extract-tag-value prompt "q") ""))
                 "search-exa"))
        ((string-equal op "vault-set")
         (harmonic-matrix-route-or-error "orchestrator" "vault")
         (let ((key (%extract-tag-value prompt "key"))
               (value (%extract-tag-value prompt "value")))
           (unless (and key value)
             (error "vault-set requires key=<symbol> value=<secret>"))
           (vault-set-secret key value)
           (values "VAULT_SET_OK" "vault")))
        ((string-equal op "parallel-solve")
         (harmonic-matrix-route-or-error "orchestrator" "parallel-agents")
         (values (parallel-solve (or (%extract-tag-value prompt "q") prompt))
                 "parallel-agents"))
        ((string-equal op "parallel-report")
         (values (parallel-report) "parallel-agents"))
        ((string-equal op "parallel-set-width")
         (let ((count (%extract-tag-value prompt "count")))
           (unless count
             (error "parallel-set-width requires count=<int>"))
           (parallel-set-subagent-count (read-from-string count))
           (values "PARALLEL_WIDTH_SET" "parallel-agents")))
        ((string-equal op "parallel-get-width")
         (values (format nil "~D" (parallel-get-subagent-count)) "parallel-agents"))
        ((string-equal op "parallel-save-policy")
         (values (parallel-save-policy) "parallel-agents"))
        ((string-equal op "parallel-load-policy")
         (parallel-load-policy)
         (values "PARALLEL_POLICY_LOADED" "parallel-agents"))
        ((string-equal op "parallel-set-price")
         (let ((model (%extract-tag-value prompt "model"))
               (in-price (%extract-tag-value prompt "in"))
               (out-price (%extract-tag-value prompt "out")))
           (unless (and model in-price out-price)
             (error "parallel-set-price requires model=<id> in=<usd/1k> out=<usd/1k>"))
           (parallel-set-model-price model
                                     (read-from-string in-price)
                                     (read-from-string out-price))
           (values "PARALLEL_PRICE_SET" "parallel-agents")))
        ((string-equal op "model-policy-get")
         (values (with-output-to-string (s) (prin1 (model-policy-get) s)) "openrouter"))
        ((string-equal op "model-policy-save")
         (values (model-policy-save) "openrouter"))
        ((string-equal op "model-policy-load")
         (model-policy-load)
         (values "MODEL_POLICY_LOADED" "openrouter"))
        ((string-equal op "model-policy-set-weight")
         (let ((metric (%extract-tag-value prompt "metric"))
               (value (%extract-tag-value prompt "value")))
           (unless (and metric value)
             (error "model-policy-set-weight requires metric=<completion|correctness|speed|price> value=<float>"))
           (model-policy-set-weight (intern (string-upcase metric) :keyword) (read-from-string value))
           (values "MODEL_POLICY_WEIGHT_SET" "openrouter")))
        ((string-equal op "model-policy-upsert")
         (let ((id (%extract-tag-value prompt "id"))
               (tier (%extract-tag-value prompt "tier"))
               (cost (%extract-tag-value prompt "cost"))
               (latency (%extract-tag-value prompt "latency"))
               (quality (%extract-tag-value prompt "quality"))
               (completion (%extract-tag-value prompt "completion"))
               (tags (%extract-tag-value prompt "tags")))
           (unless id
             (error "model-policy-upsert requires id=<model-id>"))
           (model-policy-upsert-profile
            id
            :tier (and tier (intern (string-upcase tier) :keyword))
            :cost (and cost (read-from-string cost))
            :latency (and latency (read-from-string latency))
            :quality (and quality (read-from-string quality))
            :completion (and completion (read-from-string completion))
            :tags (and tags (mapcar (lambda (x) (intern (string-upcase x) :keyword))
                                    (%split-by-comma tags))))
           (values "MODEL_POLICY_PROFILE_SET" "openrouter")))
        ((string-equal op "harmony-policy-get")
         (values (with-output-to-string (s) (prin1 (harmony-policy-get) s)) "harmonic-matrix"))
        ((string-equal op "harmony-policy-save")
         (values (harmony-policy-save) "harmonic-matrix"))
        ((string-equal op "harmony-policy-load")
         (harmony-policy-load)
         (values "HARMONY_POLICY_LOADED" "harmonic-matrix"))
        ((string-equal op "harmony-policy-set")
         (let ((path (%extract-tag-value prompt "path"))
               (value (%extract-tag-value prompt "value")))
           (unless (and path value)
             (error "harmony-policy-set requires path=<a/b/c> value=<lisp-literal>"))
           (harmony-policy-set path (read-from-string value))
           (values "HARMONY_POLICY_SET" "harmonic-matrix")))
        ((string-equal op "matrix-tool-enable")
         (harmonic-matrix-route-or-error "orchestrator" "harmonic-matrix")
         (let ((tool (%extract-tag-value prompt "tool"))
               (enabled (%extract-tag-value prompt "enabled")))
           (unless (and tool enabled)
             (error "matrix-tool-enable requires tool=<id> enabled=<1|0|t|nil>"))
           (harmonic-matrix-set-tool
            tool
            (or (string-equal enabled "1")
                (string-equal enabled "t")
                (string-equal enabled "true")))
           (values "MATRIX_TOOL_TOGGLED" "harmonic-matrix")))
        ((string-equal op "matrix-set-node")
         (harmonic-matrix-route-or-error "orchestrator" "harmonic-matrix")
         (let ((id (%extract-tag-value prompt "id"))
               (kind (%extract-tag-value prompt "kind")))
           (unless (and id kind)
             (error "matrix-set-node requires id=<node-id> kind=<core|backend|tool>"))
           (harmonic-matrix-set-node id kind)
           (values "MATRIX_NODE_SET" "harmonic-matrix")))
        ((string-equal op "matrix-set-edge")
         (harmonic-matrix-route-or-error "orchestrator" "harmonic-matrix")
         (let ((from (%extract-tag-value prompt "from"))
               (to (%extract-tag-value prompt "to"))
               (weight (%extract-tag-value prompt "weight"))
               (min (%extract-tag-value prompt "min")))
           (unless (and from to weight min)
             (error "matrix-set-edge requires from=<id> to=<id> weight=<float> min=<float>"))
           (harmonic-matrix-set-edge from to (read-from-string weight) (read-from-string min))
           (values "MATRIX_EDGE_SET" "harmonic-matrix")))
        ((string-equal op "matrix-get-topology")
         (harmonic-matrix-route-or-error "orchestrator" "harmonic-matrix")
         (values (with-output-to-string (s) (prin1 (harmonic-matrix-current-topology) s))
                 "harmonic-matrix"))
        ((string-equal op "matrix-save")
         (harmonic-matrix-route-or-error "orchestrator" "harmonic-matrix")
         (values (harmonic-matrix-save-topology) "harmonic-matrix"))
        ((string-equal op "matrix-load")
         (harmonic-matrix-route-or-error "orchestrator" "harmonic-matrix")
         (harmonic-matrix-apply-topology (harmonic-matrix-load-topology) :persist nil)
         (values "MATRIX_LOADED" "harmonic-matrix"))
        ((string-equal op "matrix-reset-defaults")
         (harmonic-matrix-route-or-error "orchestrator" "harmonic-matrix")
         (harmonic-matrix-reset-defaults)
         (values "MATRIX_DEFAULTS_RESTORED" "harmonic-matrix"))
        ((string-equal op "matrix-route-check")
         (harmonic-matrix-route-or-error "orchestrator" "harmonic-matrix")
         (let ((from (%extract-tag-value prompt "from"))
               (to (%extract-tag-value prompt "to"))
               (signal (%extract-tag-value prompt "signal"))
               (noise (%extract-tag-value prompt "noise")))
           (unless (and from to)
             (error "matrix-route-check requires from=<id> to=<id>"))
           (values (with-output-to-string (s)
                     (prin1 (harmonic-matrix-route-check from to
                                                         :signal (if signal (read-from-string signal) (getf (harmonic-matrix-route-defaults) :signal))
                                                         :noise (if noise (read-from-string noise) (getf (harmonic-matrix-route-defaults) :noise)))
                            s))
                   "harmonic-matrix")))
        ((string-equal op "matrix-route-defaults")
         (harmonic-matrix-route-or-error "orchestrator" "harmonic-matrix")
         (values (with-output-to-string (s) (prin1 (harmonic-matrix-route-defaults) s))
                 "harmonic-matrix"))
        ((string-equal op "matrix-set-route-defaults")
         (harmonic-matrix-route-or-error "orchestrator" "harmonic-matrix")
         (let ((signal (%extract-tag-value prompt "signal"))
               (noise (%extract-tag-value prompt "noise")))
           (harmonic-matrix-set-route-defaults
            :signal (and signal (read-from-string signal))
            :noise (and noise (read-from-string noise)))
           (values "MATRIX_ROUTE_DEFAULTS_SET" "harmonic-matrix")))
        ((string-equal op "matrix-report")
         (harmonic-matrix-route-or-error "orchestrator" "harmonic-matrix")
         (values (harmonic-matrix-report) "harmonic-matrix"))
        ((string-equal op "matrix-route-timeseries")
         (harmonic-matrix-route-or-error "orchestrator" "harmonic-matrix")
         (let ((from (%extract-tag-value prompt "from"))
               (to (%extract-tag-value prompt "to"))
               (limit (%extract-tag-value prompt "limit")))
           (unless (and from to)
             (error "matrix-route-timeseries requires from=<id> to=<id>"))
           (values (harmonic-matrix-route-timeseries from to (if limit (read-from-string limit) 100))
                   "harmonic-matrix")))
        ((string-equal op "matrix-time-report")
         (harmonic-matrix-route-or-error "orchestrator" "harmonic-matrix")
         (let ((since (%extract-tag-value prompt "since")))
           (values (harmonic-matrix-time-report (if since (read-from-string since) 0))
                   "harmonic-matrix")))
        ((string-equal op "whisper-transcribe")
         (harmonic-matrix-route-or-error "orchestrator" "whisper")
         (values (whisper-transcribe (or (%extract-tag-value prompt "file") ""))
                 "whisper"))
        ((string-equal op "elevenlabs-tts")
         (harmonic-matrix-route-or-error "orchestrator" "elevenlabs")
         (values (elevenlabs-tts-to-file (or (%extract-tag-value prompt "text") "")
                                         (or (%extract-tag-value prompt "voice") "JBFqnCBsd6RMkjVDRZzb")
                                         (or (%extract-tag-value prompt "out") "/tmp/harmonia-tts.mp3"))
                 "elevenlabs"))
        (t
         (error "unknown tool op: ~A" op))))))

(defun feed-prompt (prompt)
  (unless *runtime*
    (error "Runtime not initialized. Call HARMONIA:START first."))
  (memory-touch-activity)
  (ignore-errors
    (harmonic-matrix-log-event "orchestrator" "input" "prompt" (%clip-text prompt) t ""))
  (setf (runtime-state-prompt-queue *runtime*)
        (append (runtime-state-prompt-queue *runtime*) (list prompt)))
  (runtime-log *runtime* :prompt-enqueued (list :prompt prompt))
  prompt)

(defun %select-model (prompt)
  (choose-model prompt))

(defun orchestrate-once (prompt)
  (memory-touch-activity)
  (let* ((model (%select-model prompt))
         (started-at (get-internal-real-time))
         (response nil)
         (used-tool "openrouter"))
    (setf response
          (handler-case
              (multiple-value-bind (tool-res tool-id)
                  (or (let ((x (%maybe-handle-self-push-test prompt)))
                        (when x (values x "git-ops")))
                      (%maybe-handle-tool-command prompt))
                (if tool-res
                    (progn
                      (setf used-tool tool-id)
                      tool-res)
                    (progn
                      (harmonic-matrix-route-or-error "orchestrator" "openrouter")
                      (let ((chain (model-escalation-chain prompt model))
                          (result nil)
                          (ok nil))
                        (dolist (m chain)
                          (unless ok
                            (handler-case
                                (progn
                                  (setf result (backend-complete prompt m))
                                  (setf model m)
                                  (setf ok t))
                              (error (_)
                                (declare (ignore _))))))
                        (if ok
                            result
                            (error "all model attempts failed"))))))
                    (error (e)
                      (ignore-errors
                        (harmonic-matrix-log-event "orchestrator" "error" used-tool
                                                   (%clip-text prompt)
                                                   nil
                                                   (%clip-text (princ-to-string e))))
                      (error 'harmonia-backend-error
                             :phase :orchestrate
                             :detail (princ-to-string e)
                             :payload (list :prompt prompt :model model :tool used-tool)))))
    (let* ((elapsed-ms (round (* 1000
                                 (/ (- (get-internal-real-time) started-at)
                                    internal-time-units-per-second))))
           (score (harmonic-score prompt response))
           (memory-id (memory-record-orchestration prompt response used-tool score elapsed-ms)))
      (memory-record-tool-usage used-tool :latency-ms elapsed-ms :success t)
      (ignore-errors
        (harmonic-matrix-observe-route "orchestrator" used-tool t elapsed-ms))
      (ignore-errors
        (harmonic-matrix-route-or-error used-tool "memory"))
      (ignore-errors
        (harmonic-matrix-observe-route used-tool "memory" t 1))
      (ignore-errors
        (harmonic-matrix-log-event used-tool "output" "response" (%clip-text (princ-to-string response)) t ""))
      (push (list :prompt prompt
                  :response response
                  :model model
                  :score score
                  :memory-id memory-id)
            (runtime-state-responses *runtime*))
      (runtime-log *runtime* :orchestrated (list :model model :score score :memory-id memory-id))
      response)))
