;;; tool-handlers.lisp — Tool command handlers and dispatch table for conductor.

(in-package :harmonia)

;;; --- Tool command handlers (extracted from %maybe-handle-tool-command) ---

(defun %tool-cmd-gateway-send (prompt)
  (%route-or-error "orchestrator" "gateway")
  (let* ((frontend (or (%extract-tag-value prompt "channel-kind")
                       (%extract-tag-value prompt "frontend")
                       ""))
         (channel (or (%extract-tag-value prompt "address")
                      (%extract-tag-value prompt "channel")
                      "default"))
         (payload (or (%extract-tag-value prompt "payload")
                      (%extract-tag-value prompt "text") ""))
         (status (handler-case (baseband-channel-status frontend) (error () nil)))
         (has-a2ui (%capability-value (and (listp status) (getf status :capabilities))
                                      "a2ui")))
    (unless (> (length frontend) 0)
      (error "gateway-send requires channel-kind=<name>"))
    (when (and (not has-a2ui) (search "\"component\"" payload))
      (setf payload (%a2ui-extract-text payload)))
    (baseband-send frontend channel payload)
    (values (format nil "BASEBAND_SEND_OK channel-kind=~A address=~A a2ui=~A"
                    frontend channel (if has-a2ui "t" "nil"))
            "gateway")))

(defun %tool-cmd-gateway-list (prompt)
  (declare (ignore prompt))
  (%route-or-error "orchestrator" "gateway")
  (values (gateway-list-frontends) "gateway"))

(defun %tool-cmd-gateway-status (prompt)
  (%route-or-error "orchestrator" "gateway")
  (let ((name (or (%extract-tag-value prompt "name") "")))
    (values (baseband-channel-status name) "gateway")))

(defun %tool-cmd-search (prompt)
  (%route-or-error "orchestrator" "search-exa")
  (values (search-web (or (%extract-tag-value prompt "q") ""))
          "search-exa"))

(defun %tool-cmd-codemode-run (prompt)
  (let* ((steps (%extract-tag-value prompt "steps"))
         (run (%run-codemode-steps steps)))
    (values (getf run :final) "codemode" run)))

(defun %tool-cmd-vault-set (prompt)
  (%route-or-error "orchestrator" "vault")
  (let ((key (%extract-tag-value prompt "key"))
        (value (%extract-tag-value prompt "value")))
    (unless (and key value)
      (error "vault-set requires key=<symbol> value=<secret>"))
    (vault-set-secret key value)
    (values "VAULT_SET_OK" "vault")))

(defun %tool-cmd-vault-has (prompt)
  (%route-or-error "orchestrator" "vault")
  (let ((key (%extract-tag-value prompt "key")))
    (unless key
      (error "vault-has requires key=<symbol>"))
    (values (if (vault-has-secret-p key) "VAULT_HAS=1" "VAULT_HAS=0") "vault")))

(defun %tool-cmd-vault-list (prompt)
  (declare (ignore prompt))
  (%route-or-error "orchestrator" "vault")
  (values (with-output-to-string (s) (prin1 (vault-list-symbols) s)) "vault"))

(defun %tool-cmd-config-set (prompt)
  (%route-or-error "orchestrator" "harmonic-matrix")
  (let ((key (%extract-tag-value prompt "key"))
        (value (%extract-tag-value prompt "value")))
    (unless (and key value)
      (error "config-set requires key=<symbol> value=<text>"))
    (config-set key value)
    (values "CONFIG_SET_OK" "harmonic-matrix")))

(defun %tool-cmd-config-get (prompt)
  (%route-or-error "orchestrator" "harmonic-matrix")
  (let ((key (%extract-tag-value prompt "key")))
    (unless key
      (error "config-get requires key=<symbol>"))
    (values (or (config-get key) "CONFIG_MISSING") "harmonic-matrix")))

(defun %tool-cmd-config-list (prompt)
  (declare (ignore prompt))
  (%route-or-error "orchestrator" "harmonic-matrix")
  (values (with-output-to-string (s) (prin1 (config-list) s)) "harmonic-matrix"))

(defun %tool-cmd-parallel-solve (prompt)
  (%route-or-error "orchestrator" "parallel-agents")
  (values (parallel-solve (or (%extract-tag-value prompt "q") prompt))
          "parallel-agents"))

(defun %tool-cmd-parallel-report (prompt)
  (declare (ignore prompt))
  (values (parallel-report) "parallel-agents"))

(defun %tool-cmd-parallel-set-width (prompt)
  (let ((count (%extract-tag-value prompt "count")))
    (unless count
      (error "parallel-set-width requires count=<int>"))
    (parallel-set-subagent-count (%safe-parse-number count))
    (values "PARALLEL_WIDTH_SET" "parallel-agents")))

(defun %tool-cmd-parallel-get-width (prompt)
  (declare (ignore prompt))
  (values (format nil "~D" (parallel-get-subagent-count)) "parallel-agents"))

(defun %tool-cmd-parallel-save-policy (prompt)
  (declare (ignore prompt))
  (values (parallel-save-policy) "parallel-agents"))

(defun %tool-cmd-parallel-load-policy (prompt)
  (declare (ignore prompt))
  (parallel-load-policy)
  (values "PARALLEL_POLICY_LOADED" "parallel-agents"))

(defun %tool-cmd-parallel-set-price (prompt)
  (let ((model (%extract-tag-value prompt "model"))
        (in-price (%extract-tag-value prompt "in"))
        (out-price (%extract-tag-value prompt "out")))
    (unless (and model in-price out-price)
      (error "parallel-set-price requires model=<id> in=<usd/1k> out=<usd/1k>"))
    (parallel-set-model-price model
                              (%safe-parse-number in-price)
                              (%safe-parse-number out-price))
    (values "PARALLEL_PRICE_SET" "parallel-agents")))

(defun %tool-cmd-model-policy-get (prompt)
  (declare (ignore prompt))
  (values (with-output-to-string (s) (prin1 (model-policy-get) s)) "provider-router"))

(defun %tool-cmd-model-policy-save (prompt)
  (declare (ignore prompt))
  (values (model-policy-save) "provider-router"))

(defun %tool-cmd-model-policy-load (prompt)
  (declare (ignore prompt))
  (model-policy-load)
  (values "MODEL_POLICY_LOADED" "provider-router"))

(defun %tool-cmd-model-policy-set-weight (prompt)
  (let ((metric (%extract-tag-value prompt "metric"))
        (value (%extract-tag-value prompt "value")))
    (unless (and metric value)
      (error "model-policy-set-weight requires metric=<completion|correctness|speed|price|token-efficiency|orchestration-efficiency> value=<float>"))
    (model-policy-set-weight (intern (string-upcase metric) :keyword) (%safe-parse-number value))
    (values "MODEL_POLICY_WEIGHT_SET" "provider-router")))

(defun %tool-cmd-model-policy-upsert (prompt)
  (let ((id (%extract-tag-value prompt "id"))
        (tier (%extract-tag-value prompt "tier"))
        (cost (%extract-tag-value prompt "cost"))
        (latency (%extract-tag-value prompt "latency"))
        (quality (%extract-tag-value prompt "quality"))
        (completion (%extract-tag-value prompt "completion"))
        (tags (%extract-tag-value prompt "tags")))
    (unless id
      (error "model-policy-upsert requires id=<model-id>"))
    (model-policy-upsert-profile
     id
     :tier (and tier (intern (string-upcase tier) :keyword))
     :cost (and cost (%safe-parse-number cost))
     :latency (and latency (%safe-parse-number latency))
     :quality (and quality (%safe-parse-number quality))
     :completion (and completion (%safe-parse-number completion))
     :tags (and tags (mapcar (lambda (x) (intern (string-upcase x) :keyword))
                             (%split-by-comma tags))))
    (values "MODEL_POLICY_PROFILE_SET" "provider-router")))

(defun %tool-cmd-harmony-policy-get (prompt)
  (declare (ignore prompt))
  (values (with-output-to-string (s) (prin1 (harmony-policy-get) s)) "harmonic-matrix"))

(defun %tool-cmd-harmony-policy-save (prompt)
  (declare (ignore prompt))
  (values (harmony-policy-save) "harmonic-matrix"))

(defun %tool-cmd-harmony-policy-load (prompt)
  (declare (ignore prompt))
  (harmony-policy-load)
  (values "HARMONY_POLICY_LOADED" "harmonic-matrix"))

(defun %tool-cmd-harmony-policy-set (prompt)
  (let ((path (%extract-tag-value prompt "path"))
        (value (%extract-tag-value prompt "value")))
    (unless (and path value)
      (error "harmony-policy-set requires path=<a/b/c> value=<lisp-literal>"))
    (let ((parsed-value (%safe-parse-policy-value value)))
      (%invariant-guard "harmony-policy-set" (list :path path :value parsed-value))
      (harmony-policy-set path parsed-value))
    (values "HARMONY_POLICY_SET" "harmonic-matrix")))

(defun %tool-cmd-matrix-tool-enable (prompt)
  (%route-or-error "orchestrator" "harmonic-matrix")
  (let ((tool (%extract-tag-value prompt "tool"))
        (enabled (%extract-tag-value prompt "enabled")))
    (unless (and tool enabled)
      (error "matrix-tool-enable requires tool=<id> enabled=<1|0|t|nil>"))
    (harmonic-matrix-set-tool
     tool
     (or (string-equal enabled "1")
         (string-equal enabled "t")
         (string-equal enabled "true")))
    (values "MATRIX_TOOL_TOGGLED" "harmonic-matrix")))

(defun %tool-cmd-matrix-set-node (prompt)
  (%route-or-error "orchestrator" "harmonic-matrix")
  (let ((id (%extract-tag-value prompt "id"))
        (kind (%extract-tag-value prompt "kind")))
    (unless (and id kind)
      (error "matrix-set-node requires id=<node-id> kind=<core|backend|tool>"))
    (harmonic-matrix-set-node id kind)
    (values "MATRIX_NODE_SET" "harmonic-matrix")))

(defun %tool-cmd-matrix-set-store (prompt)
  (%route-or-error "orchestrator" "harmonic-matrix")
  (let ((kind (%extract-tag-value prompt "kind"))
        (path (%extract-tag-value prompt "path")))
    (unless kind
      (error "matrix-set-store requires kind=<memory|sqlite|graph>"))
    (harmonic-matrix-set-store kind (or path ""))
    (values "MATRIX_STORE_SET" "harmonic-matrix")))

(defun %tool-cmd-matrix-get-store (prompt)
  (declare (ignore prompt))
  (%route-or-error "orchestrator" "harmonic-matrix")
  (values (harmonic-matrix-store-config) "harmonic-matrix"))

(defun %tool-cmd-matrix-set-edge (prompt)
  (%route-or-error "orchestrator" "harmonic-matrix")
  (let ((from (%extract-tag-value prompt "from"))
        (to (%extract-tag-value prompt "to"))
        (weight (%extract-tag-value prompt "weight"))
        (min (%extract-tag-value prompt "min")))
    (unless (and from to weight min)
      (error "matrix-set-edge requires from=<id> to=<id> weight=<float> min=<float>"))
    (let ((w (%safe-parse-number weight))
          (m (%safe-parse-number min)))
      (%invariant-guard "matrix-set-edge" (list :to to :min-harmony m))
      (harmonic-matrix-set-edge from to w m))
    (values "MATRIX_EDGE_SET" "harmonic-matrix")))

(defun %tool-cmd-matrix-get-topology (prompt)
  (declare (ignore prompt))
  (%route-or-error "orchestrator" "harmonic-matrix")
  (values (with-output-to-string (s) (prin1 (harmonic-matrix-current-topology) s))
          "harmonic-matrix"))

(defun %tool-cmd-matrix-save (prompt)
  (declare (ignore prompt))
  (%route-or-error "orchestrator" "harmonic-matrix")
  (values (harmonic-matrix-save-topology) "harmonic-matrix"))

(defun %tool-cmd-matrix-load (prompt)
  (declare (ignore prompt))
  (%route-or-error "orchestrator" "harmonic-matrix")
  (harmonic-matrix-apply-topology (harmonic-matrix-load-topology) :persist nil)
  (values "MATRIX_LOADED" "harmonic-matrix"))

(defun %tool-cmd-matrix-reset-defaults (prompt)
  (declare (ignore prompt))
  (%route-or-error "orchestrator" "harmonic-matrix")
  (harmonic-matrix-reset-defaults)
  (values "MATRIX_DEFAULTS_RESTORED" "harmonic-matrix"))

(defun %tool-cmd-matrix-route-check (prompt)
  (%route-or-error "orchestrator" "harmonic-matrix")
  (let ((from (%extract-tag-value prompt "from"))
        (to (%extract-tag-value prompt "to"))
        (signal (%extract-tag-value prompt "signal"))
        (noise (%extract-tag-value prompt "noise")))
    (unless (and from to)
      (error "matrix-route-check requires from=<id> to=<id>"))
    (values (with-output-to-string (s)
              (prin1 (harmonic-matrix-route-check from to
                                                  :signal (if signal (%safe-parse-number signal) (getf (harmonic-matrix-route-defaults) :signal))
                                                  :noise (if noise (%safe-parse-number noise) (getf (harmonic-matrix-route-defaults) :noise)))
                     s))
            "harmonic-matrix")))

(defun %tool-cmd-matrix-route-defaults (prompt)
  (declare (ignore prompt))
  (%route-or-error "orchestrator" "harmonic-matrix")
  (values (with-output-to-string (s) (prin1 (harmonic-matrix-route-defaults) s))
          "harmonic-matrix"))

(defun %tool-cmd-matrix-set-route-defaults (prompt)
  (%route-or-error "orchestrator" "harmonic-matrix")
  (let ((signal (%extract-tag-value prompt "signal"))
        (noise (%extract-tag-value prompt "noise")))
    (harmonic-matrix-set-route-defaults
     :signal (and signal (%safe-parse-number signal))
     :noise (and noise (%safe-parse-number noise)))
    (values "MATRIX_ROUTE_DEFAULTS_SET" "harmonic-matrix")))

(defun %tool-cmd-matrix-report (prompt)
  (declare (ignore prompt))
  (%route-or-error "orchestrator" "harmonic-matrix")
  (values (harmonic-matrix-report) "harmonic-matrix"))

(defun %tool-cmd-matrix-route-timeseries (prompt)
  (%route-or-error "orchestrator" "harmonic-matrix")
  (let ((from (%extract-tag-value prompt "from"))
        (to (%extract-tag-value prompt "to"))
        (limit (%extract-tag-value prompt "limit")))
    (unless (and from to)
      (error "matrix-route-timeseries requires from=<id> to=<id>"))
    (values (harmonic-matrix-route-timeseries from to (if limit (%safe-parse-number limit) 100))
            "harmonic-matrix")))

(defun %tool-cmd-matrix-time-report (prompt)
  (%route-or-error "orchestrator" "harmonic-matrix")
  (let ((since (%extract-tag-value prompt "since")))
    (values (harmonic-matrix-time-report (if since (%safe-parse-number since) 0))
            "harmonic-matrix")))

(defun %tool-cmd-whisper-transcribe (prompt)
  (%route-or-error "orchestrator" "whisper")
  (values (whisper-transcribe (or (%extract-tag-value prompt "file") ""))
          "whisper"))

(defun %tool-cmd-elevenlabs-tts (prompt)
  (%route-or-error "orchestrator" "elevenlabs")
  (values (elevenlabs-tts-to-file (or (%extract-tag-value prompt "text") "")
                                  (or (%extract-tag-value prompt "voice") (%default-tts-voice))
                                  (or (%extract-tag-value prompt "out") (%default-tts-output)))
          "elevenlabs"))

;;; --- Tool dispatch table ---

(defparameter *tool-dispatch-table*
  '(("gateway-send"             . %tool-cmd-gateway-send)
    ("gateway-list"             . %tool-cmd-gateway-list)
    ("gateway-status"           . %tool-cmd-gateway-status)
    ("search"                   . %tool-cmd-search)
    ("codemode-run"             . %tool-cmd-codemode-run)
    ("vault-set"                . %tool-cmd-vault-set)
    ("vault-has"                . %tool-cmd-vault-has)
    ("vault-list"               . %tool-cmd-vault-list)
    ("config-set"               . %tool-cmd-config-set)
    ("config-get"               . %tool-cmd-config-get)
    ("config-list"              . %tool-cmd-config-list)
    ("parallel-solve"           . %tool-cmd-parallel-solve)
    ("parallel-report"          . %tool-cmd-parallel-report)
    ("parallel-set-width"       . %tool-cmd-parallel-set-width)
    ("parallel-get-width"       . %tool-cmd-parallel-get-width)
    ("parallel-save-policy"     . %tool-cmd-parallel-save-policy)
    ("parallel-load-policy"     . %tool-cmd-parallel-load-policy)
    ("parallel-set-price"       . %tool-cmd-parallel-set-price)
    ("model-policy-get"         . %tool-cmd-model-policy-get)
    ("model-policy-save"        . %tool-cmd-model-policy-save)
    ("model-policy-load"        . %tool-cmd-model-policy-load)
    ("model-policy-set-weight"  . %tool-cmd-model-policy-set-weight)
    ("model-policy-upsert"      . %tool-cmd-model-policy-upsert)
    ("harmony-policy-get"       . %tool-cmd-harmony-policy-get)
    ("harmony-policy-save"      . %tool-cmd-harmony-policy-save)
    ("harmony-policy-load"      . %tool-cmd-harmony-policy-load)
    ("harmony-policy-set"       . %tool-cmd-harmony-policy-set)
    ("matrix-tool-enable"       . %tool-cmd-matrix-tool-enable)
    ("matrix-set-node"          . %tool-cmd-matrix-set-node)
    ("matrix-set-store"         . %tool-cmd-matrix-set-store)
    ("matrix-get-store"         . %tool-cmd-matrix-get-store)
    ("matrix-set-edge"          . %tool-cmd-matrix-set-edge)
    ("matrix-get-topology"      . %tool-cmd-matrix-get-topology)
    ("matrix-save"              . %tool-cmd-matrix-save)
    ("matrix-load"              . %tool-cmd-matrix-load)
    ("matrix-reset-defaults"    . %tool-cmd-matrix-reset-defaults)
    ("matrix-route-check"       . %tool-cmd-matrix-route-check)
    ("matrix-route-defaults"    . %tool-cmd-matrix-route-defaults)
    ("matrix-set-route-defaults" . %tool-cmd-matrix-set-route-defaults)
    ("matrix-report"            . %tool-cmd-matrix-report)
    ("matrix-route-timeseries"  . %tool-cmd-matrix-route-timeseries)
    ("matrix-time-report"       . %tool-cmd-matrix-time-report)
    ("whisper-transcribe"       . %tool-cmd-whisper-transcribe)
    ("elevenlabs-tts"           . %tool-cmd-elevenlabs-tts))
  "Alist mapping tool operation names to handler functions.
Each handler takes PROMPT and returns (values result tool-id &optional metadata).")

(defun %maybe-handle-tool-command (prompt)
  "Dispatch tool commands through the dispatch table. Policy-gated."
  ;; Only match explicit tool command syntax: "tool op=<name>"
  ;; Not any text that happens to contain the word "tool".
  (when (and (search "tool " prompt :test #'char-equal)
             (%extract-tag-value prompt "op"))
    (let* ((op (%extract-tag-value prompt "op"))
           (handler (cdr (assoc op *tool-dispatch-table* :test #'string-equal))))
      ;; Wave 1.5: Policy gate — check if operation is allowed given current signal context
      (%policy-gate op *current-originating-signal* prompt)
      (if handler
          (funcall handler prompt)
          (error "unknown tool op: ~A" op)))))
