;;; bootstrap.lisp — Memory bootstrap, semantic recall, and journal.

(in-package :harmonia)

(defun %current-day-number (&optional ut)
  (floor (or ut (get-universal-time)) 86400))

(defun %yesterday-dailies ()
  "Return daily entries from the previous calendar day."
  (let* ((now (get-universal-time))
         (today-day (%current-day-number now))
         (yesterday-day (1- today-day))
         (results '()))
    (dolist (id (gethash :daily *memory-by-class*))
      (let ((entry (gethash id *memory-store*)))
        (when (and entry
                   (= (%current-day-number (memory-entry-time entry)) yesterday-day))
          (push entry results))))
    (sort results #'> :key #'memory-entry-time)))

(defun memory-bootstrap-skills (query &key (limit 3) (max-chars 1200))
  "Return string block of top-N skills matching QUERY."
  (let* ((needle (string-downcase (or query "")))
         (scored '()))
    (dolist (id (gethash :skill *memory-by-class*))
      (let* ((entry (gethash id *memory-store*))
             (text (%entry-text entry))
             (score (+ (* 10 (memory-entry-depth entry))
                       (memory-entry-access-count entry)
                       (if (search needle (string-downcase text) :test #'char-equal) 20 0))))
        (when entry
          (push (cons score entry) scored))))
    (let* ((sorted (subseq (sort scored #'> :key #'car) 0 (min limit (length scored))))
           (out (make-string-output-stream))
           (total 0))
      (dolist (pair sorted)
        (let* ((entry (cdr pair))
               (text (%entry-text entry))
               (clipped (subseq text 0 (min 300 (length text)))))
          (when (< total max-chars)
            (write-string "- " out)
            (write-string clipped out)
            (terpri out)
            (incf total (+ 2 (length clipped) 1)))))
      (get-output-stream-string out))))

(defun memory-bootstrap-recent (&key (limit 5) (max-chars 800))
  "Return string block of last K daily prompts."
  (let* ((recents (memory-recent :limit limit :class :daily :max-depth 0))
         (out (make-string-output-stream))
         (total 0))
    (dolist (entry recents)
      (let* ((payload (memory-entry-content entry))
             (prompt (if (and (listp payload) (getf payload :prompt))
                         (getf payload :prompt)
                         ""))
             (clipped (subseq prompt 0 (min 120 (length prompt)))))
        (when (and (> (length clipped) 0) (< total max-chars))
          (write-string "- " out)
          (write-string clipped out)
          (terpri out)
          (incf total (+ 2 (length clipped) 1)))))
    (get-output-stream-string out)))

(defun memory-bootstrap-context (query &key (mode :orchestrate))
  "Assemble full bootstrap block. Returns empty string for :planner mode."
  (when (eq mode :planner)
    (return-from memory-bootstrap-context ""))
  (let* ((skill-limit (signalograd-memory-bootstrap-skill-limit *runtime*))
         (skill-chars (truncate (if (fboundp 'harmony-policy-number)
                                    (harmony-policy-number "memory/bootstrap-skill-chars" 1200)
                                    1200)))
         (recent-limit (truncate (if (fboundp 'harmony-policy-number)
                                     (harmony-policy-number "memory/bootstrap-recent-limit" 5)
                                     5)))
         (recent-chars (truncate (if (fboundp 'harmony-policy-number)
                                     (harmony-policy-number "memory/bootstrap-recent-chars" 800)
                                     800)))
         (skills (memory-bootstrap-skills (or query "") :limit skill-limit :max-chars skill-chars))
         (recent (memory-bootstrap-recent :limit recent-limit :max-chars recent-chars))
         (has-skills (> (length skills) 0))
         (has-recent (> (length recent) 0)))
    (if (or has-skills has-recent)
        (with-output-to-string (out)
          (terpri out)
          (terpri out)
          (when has-skills
            (write-string "RELEVANT_SKILLS:" out)
            (terpri out)
            (write-string skills out))
          (when has-recent
            (write-string "RECENT_CONTEXT:" out)
            (terpri out)
            (write-string recent out)))
        "")))

(defun memory-semantic-recall-block (query &key (limit 5) (max-chars 1500))
  "Recall from memory field. If query produces no concepts after stopwords,
fall back to high-depth entries — crystallized = structural = identity."
  (let* ((results (or (memory-layered-recall query :limit limit)
                      ;; Fallback: high-depth entries (crystallized by dreaming or seeded by DNA).
                      (%memory-by-depth limit 1)
                      (memory-recent :limit limit)))
         (out (make-string-output-stream))
         (total 0))
    (when results
      (terpri out)
      (terpri out)
      (write-string "MEMORY_RECALL:" out)
      (terpri out)
      (dolist (entry results)
        (let* ((text (%entry-text entry))
               (depth (memory-entry-depth entry))
               (prefix (format nil "[d~D] " depth))
               (clipped (subseq text 0 (min 300 (length text)))))
          (when (< total max-chars)
            (write-string "- " out)
            (write-string prefix out)
            (write-string clipped out)
            (terpri out)
            (incf total (+ 2 (length prefix) (length clipped) 1))))))
    (get-output-stream-string out)))

(defun memory-maybe-journal-yesterday ()
  "On first interaction of a new day, create a skill summarizing yesterday's dailies."
  (let ((today (%current-day-number)))
    (when (= *memory-last-journal-day* today)
      (return-from memory-maybe-journal-yesterday nil))
    (setf *memory-last-journal-day* today)
    (let ((yesterdays (%yesterday-dailies)))
      (when (and yesterdays (> (length yesterdays) 0))
        (let* ((count (length yesterdays))
               (scores (remove nil
                         (mapcar (lambda (e)
                                   (let ((p (memory-entry-content e)))
                                     (when (and (listp p) (numberp (getf p :score)))
                                       (getf p :score))))
                                 yesterdays)))
               (avg-score (if scores (/ (reduce #'+ scores) (float (length scores))) 0.0))
               (topics (remove-duplicates
                         (mapcan (lambda (e)
                                   (let* ((p (memory-entry-content e))
                                          (prompt (if (and (listp p) (stringp (getf p :prompt)))
                                                      (getf p :prompt) ""))
                                          (words (%split-words prompt)))
                                     (subseq words 0 (min 3 (length words)))))
                                 yesterdays)
                         :test #'string=)))
          (memory-put :skill
                      (format nil "Daily journal: ~D interactions, avg score ~,2F, topics: ~{~A~^, ~}"
                              count avg-score topics)
                      :depth 1
                      :tags (list :journal :daily-summary :temporal)))))))
