(:nodes (("orchestrator" . "core")
         ("memory" . "core")
         ("vault" . "core")
         ("openrouter" . "backend")
         ("parallel-agents" . "core")
         ("search-exa" . "core")
         ("search-brave" . "core")
         ("harmonic-matrix" . "core")
         ("whatsapp" . "tool")
         ("telegram" . "tool")
         ("slack" . "tool")
         ("mattermost" . "tool")
         ("nostr" . "tool")
         ("email-client" . "tool")
         ("whisper" . "tool")
         ("elevenlabs" . "tool")
         ("git-ops" . "core")
         ("gateway" . "core"))
 :edges (("orchestrator" "openrouter" 1.15 0.35)
         ("orchestrator" "parallel-agents" 1.10 0.30)
         ("orchestrator" "search-exa" 1.20 0.20)
         ("orchestrator" "search-brave" 1.10 0.20)
         ("orchestrator" "vault" 1.20 0.70)
         ("orchestrator" "harmonic-matrix" 1.20 0.60)
         ("orchestrator" "memory" 1.25 0.10)
         ("orchestrator" "whatsapp" 1.00 0.10)
         ("orchestrator" "telegram" 1.00 0.10)
         ("orchestrator" "slack" 1.00 0.10)
         ("orchestrator" "mattermost" 1.00 0.10)
         ("orchestrator" "nostr" 0.95 0.10)
         ("orchestrator" "email-client" 1.05 0.10)
         ("orchestrator" "whisper" 1.00 0.10)
         ("orchestrator" "elevenlabs" 1.00 0.10)
         ("orchestrator" "gateway" 1.20 0.15)
         ("orchestrator" "git-ops" 1.20 0.55)
         ("parallel-agents" "openrouter" 1.05 0.25)
         ("parallel-agents" "search-exa" 1.10 0.20)
         ("parallel-agents" "search-brave" 1.05 0.20)
         ("harmonic-matrix" "memory" 0.95 0.05)
         ("vault" "memory" 0.95 0.05)
         ("openrouter" "memory" 0.95 0.05)
         ("search-exa" "memory" 1.00 0.05)
         ("search-brave" "memory" 0.95 0.05)
         ("whatsapp" "memory" 0.90 0.05)
         ("telegram" "memory" 0.90 0.05)
         ("slack" "memory" 0.90 0.05)
         ("mattermost" "memory" 0.90 0.05)
         ("nostr" "memory" 0.90 0.05)
         ("email-client" "memory" 0.90 0.05)
         ("whisper" "memory" 0.90 0.05)
         ("elevenlabs" "memory" 0.90 0.05)
         ("parallel-agents" "memory" 0.95 0.05)
         ("git-ops" "memory" 0.95 0.05)
         ("gateway" "memory" 0.95 0.05))
 :tools (("whatsapp" . t)
         ("telegram" . t)
         ("slack" . t)
         ("mattermost" . t)
         ("nostr" . t)
         ("email-client" . t)
         ("whisper" . t)
         ("elevenlabs" . t)))
