;;; tools.lisp — Tool registry and status inspection.

(in-package :harmonia)

(defun register-tool (runtime id path)
  (setf (gethash id (runtime-state-tools runtime))
        (list :id id :path path :status :registered :loaded-at nil)))

(defun register-default-tools (runtime)
  (dolist (tool '(("phoenix" . "lib/core/phoenix")
                  ("ouroboros" . "lib/core/ouroboros")
                  ("vault" . "lib/core/vault")
                  ("memory" . "lib/core/memory")
                  ("mqtt-client" . "lib/core/mqtt-client")
                  ("http" . "lib/core/http")
                  ("s3-sync" . "lib/core/s3-sync")
                  ("git-ops" . "lib/core/git-ops")
                  ("rust-forge" . "lib/core/rust-forge")
                  ("cron-scheduler" . "lib/core/cron-scheduler")
                  ("push-sns" . "lib/core/push-sns")
                  ("recovery" . "lib/core/recovery")
                  ("browser" . "lib/core/browser")
                  ("fs" . "lib/core/fs")
                  ("openrouter-backend" . "lib/backends/openrouter-backend")
                  ("pgp-identity" . "lib/tools/pgp-identity")
                  ("webcash-wallet" . "lib/tools/webcash-wallet")
                  ("social" . "lib/tools/social")))
    (register-tool runtime (car tool) (cdr tool)))
  runtime)

(defun tool-status (&optional (runtime *runtime*))
  (let ((out '()))
    (maphash (lambda (key value)
               (declare (ignore key))
               (push value out))
             (runtime-state-tools runtime))
    (sort out #'string< :key (lambda (item) (getf item :id)))))
