#!/usr/bin/env bash
set -euo pipefail
export LC_ALL=C

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
REF_DIR="${ROOT_DIR}/doc/reference"
MIGRATION_MAP="${REF_DIR}/migration-map.md"
OUT_FILE="${1:-${REF_DIR}/source-section-coverage.md}"

if [[ ! -f "${MIGRATION_MAP}" ]]; then
  echo "[doc-coverage] migration map not found: ${MIGRATION_MAP}" >&2
  exit 1
fi

if [[ -d "${ROOT_DIR}/../doc/agent/genesis" && -d "${ROOT_DIR}/../doc/agent/evolution/latest" ]]; then
  CANON_GENESIS="${ROOT_DIR}/../doc/agent/genesis"
  CANON_EVOLUTION="${ROOT_DIR}/../doc/agent/evolution/latest"
  SOURCE_PREFIX="../../../doc/agent"
  SCOPE_DESC='`doc/agent/genesis`, `doc/agent/evolution/latest`'
elif [[ -d "${ROOT_DIR}/src/boot/genesis" && -d "${ROOT_DIR}/src/boot/evolution/latest" ]]; then
  CANON_GENESIS="${ROOT_DIR}/src/boot/genesis"
  CANON_EVOLUTION="${ROOT_DIR}/src/boot/evolution/latest"
  SOURCE_PREFIX="../../src/boot"
  SCOPE_DESC='`src/boot/genesis`, `src/boot/evolution/latest`'
else
  echo "[doc-coverage] canonical docs missing under doc/agent and src/boot" >&2
  exit 1
fi

trim() {
  sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//'
}

doc_source_ref() {
  local doc="$1"
  if [[ "${doc}" == "${CANON_GENESIS}"/* ]]; then
    printf '%s/genesis/%s' "${SOURCE_PREFIX}" "${doc#${CANON_GENESIS}/}"
  else
    printf '%s/evolution/latest/%s' "${SOURCE_PREFIX}" "${doc#${CANON_EVOLUTION}/}"
  fi
}

DOCS=()
while IFS= read -r doc; do
  DOCS+=("${doc}")
done < <(
  {
    find "${CANON_GENESIS}" -maxdepth 1 -type f -name '*.md' -print
    find "${CANON_EVOLUTION}" -maxdepth 1 -type f -name '*.md' -print
  } | sort
)

{
  echo "# Source Section Coverage Matrix"
  echo
  echo 'This file is generated by `scripts/generate-doc-section-coverage.sh`.'
  echo "Do not edit manually."
  echo
  echo "## Scope"
  echo "- Canonical roots: ${SCOPE_DESC}"
  echo "- Files indexed: ${#DOCS[@]}"
  echo

  for doc in "${DOCS[@]}"; do
    source_ref="$(doc_source_ref "${doc}")"
    map_pattern="$(printf '| `%s` |' "${source_ref}")"
    row="$(grep -F "${map_pattern}" "${MIGRATION_MAP}" || true)"
    targets=""
    if [[ -n "${row}" ]]; then
      targets="$(printf '%s\n' "${row}" | awk -F'|' '{print $4}' | trim)"
    fi

    printf '## `%s`\n' "${source_ref}"
    if [[ -n "${targets}" ]]; then
      echo "- Migration map targets: ${targets}"
    else
      echo "- Migration map targets: **MISSING**"
    fi

    headings="$(grep -n '^##\{1,2\} ' "${doc}" || true)"
    if [[ -z "${headings}" ]]; then
      echo "- Headings: _(no level-2/3 headings found)_"
      echo
      continue
    fi

    echo "- Headings:"
    while IFS= read -r line; do
      ln="${line%%:*}"
      text="${line#*:}"
      printf '  - L%s: `%s`\n' "${ln}" "${text}"
    done <<< "${headings}"
    echo
  done
} > "${OUT_FILE}"

echo "[doc-coverage] wrote ${OUT_FILE}"
