/// Static keyword sets — all lowercase ASCII &str constants.
/// Zero heap allocation: compiled into the binary's .rodata section.
/// Dimensions module lowercases input once, then uses std's optimized str::contains.

pub static REASONING_KEYWORDS: &[&str] = &[
    "prove",
    "theorem",
    "step-by-step",
    "step by step",
    "analyze",
    "analyse",
    "evaluate",
    "compare and contrast",
    "derive",
    "deduce",
    "infer",
    "reason",
    "reasoning",
    "logic",
    "logical",
    "argument",
    "hypothesis",
    "synthesize",
    "critique",
    "counterargument",
    "trade-off",
    "tradeoff",
    "implications",
    "root cause",
    "why does",
    "explain why",
    "what causes",
    "mathematical proof",
    "formal verification",
    "chain of thought",
    "think through",
];

pub static CODE_KEYWORDS: &[&str] = &[
    "function",
    "async",
    "await",
    "import",
    "export",
    "class",
    "struct",
    "enum",
    "trait",
    "impl",
    "def ",
    "fn ",
    "pub fn",
    "const ",
    "let ",
    "var ",
    "return",
    "if ",
    "else ",
    "for ",
    "while ",
    "match ",
    "switch",
    "interface",
    "module",
    "package",
    "require",
    "use ",
    "from ",
    "```",
    "lambda",
    "defun",
    "defn",
    "println",
    "console.log",
    "print(",
    "fmt.",
    "std::",
    "self.",
    "this.",
    "#include",
    "#define",
];

pub static TECHNICAL_TERMS: &[&str] = &[
    "algorithm",
    "data structure",
    "database",
    "api",
    "endpoint",
    "middleware",
    "microservice",
    "kubernetes",
    "docker",
    "terraform",
    "oauth",
    "jwt",
    "encryption",
    "hash",
    "protocol",
    "tcp",
    "http",
    "websocket",
    "grpc",
    "graphql",
    "sql",
    "nosql",
    "cache",
    "index",
    "shard",
    "replica",
    "consensus",
    "distributed",
    "concurrent",
    "mutex",
    "semaphore",
    "deadlock",
    "race condition",
    "garbage collection",
    "memory leak",
    "stack overflow",
    "heap",
    "binary tree",
    "linked list",
    "hash map",
    "neural network",
    "gradient",
    "backpropagation",
    "transformer",
    "embedding",
    "tokenizer",
    "llm",
    "inference",
    "latency",
    "throughput",
    "bandwidth",
    "compiler",
    "parser",
    "lexer",
    "ast",
    "bytecode",
    "jit",
    "virtual machine",
    "syscall",
    "kernel",
    "filesystem",
    "raft",
    "paxos",
    "cqrs",
    "event sourcing",
];

pub static CREATIVE_MARKERS: &[&str] = &[
    "write a story",
    "compose",
    "creative",
    "poem",
    "poetry",
    "fiction",
    "narrative",
    "imagine",
    "brainstorm",
    "come up with",
    "invent",
    "generate ideas",
    "write a song",
    "screenplay",
    "dialogue",
    "character",
    "plot",
    "metaphor",
    "artistic",
    "design a",
];

pub static SIMPLE_INDICATORS: &[&str] = &[
    "hello",
    "hi",
    "hey",
    "thanks",
    "thank you",
    "yes",
    "no",
    "ok",
    "okay",
    "sure",
    "bye",
    "goodbye",
    "good morning",
    "good night",
    "how are you",
    "what time",
    "what date",
    "who are you",
    "what is your name",
    "ping",
    "test",
    "help",
];

pub static MULTI_STEP_PATTERNS: &[&str] = &[
    "first,",
    "first ",
    "then ",
    "next,",
    "next ",
    "finally,",
    "finally ",
    "step 1",
    "step 2",
    "step 3",
    "1)",
    "2)",
    "3)",
    "1.",
    "2.",
    "3.",
    "after that",
    "once done",
    "followed by",
    "in addition",
    "and then",
    "subsequently",
    "phase 1",
    "phase 2",
];

pub static CONSTRAINT_KEYWORDS: &[&str] = &[
    "must",
    "require",
    "constraint",
    "ensure",
    "guarantee",
    "enforce",
    "validate",
    "verify",
    "assert",
    "boundary",
    "limit",
    "restrict",
    "comply",
    "compliance",
    "backward compat",
    "backwards compat",
    "no breaking change",
    "non-breaking",
    "idempotent",
    "thread-safe",
    "atomic",
    "exactly once",
    "at least once",
    "at most once",
    "timeout",
    "retry",
    "fallback",
    "graceful",
    "deterministic",
];

pub static OUTPUT_FORMAT_KEYWORDS: &[&str] = &[
    "json",
    "csv",
    "xml",
    "yaml",
    "toml",
    "markdown",
    "table",
    "spreadsheet",
    "bullet point",
    "numbered list",
    "format as",
    "output as",
    "return as",
    "in the format",
    "schema",
    "structured",
    "template",
    "s-expression",
    "sexp",
    "html",
    "latex",
    "svg",
];

pub static REFERENCE_KEYWORDS: &[&str] = &[
    "according to",
    "reference",
    "citation",
    "source",
    "paper",
    "study",
    "research",
    "documentation",
    "spec",
    "specification",
    "rfc",
    "standard",
    "ieee",
    "iso",
    "w3c",
    "ietf",
    "peer-reviewed",
    "academic",
    "journal",
];

pub static NEGATION_KEYWORDS: &[&str] = &[
    "not",
    "don't",
    "doesn't",
    "shouldn't",
    "without",
    "except",
    "unless",
    "exclude",
    "avoid",
    "never",
    "nor",
    "neither",
    "but not",
    "instead of",
    "rather than",
    "however",
    "although",
    "despite",
    "regardless",
    "notwithstanding",
];

pub static IMPERATIVE_VERBS: &[&str] = &[
    "implement",
    "create",
    "build",
    "write",
    "develop",
    "design",
    "refactor",
    "optimize",
    "fix",
    "debug",
    "deploy",
    "configure",
    "setup",
    "set up",
    "install",
    "migrate",
    "upgrade",
    "integrate",
    "test",
    "benchmark",
    "profile",
    "document",
    "rewrite",
    "extend",
    "modify",
    "update",
    "add",
    "remove",
    "delete",
    "replace",
    "convert",
    "transform",
    "generate",
    "compile",
    "parse",
    "serialize",
];

pub static DOMAIN_SPECIFIC: &[&str] = &[
    "medical",
    "clinical",
    "diagnosis",
    "legal",
    "contract",
    "compliance",
    "financial",
    "trading",
    "portfolio",
    "actuarial",
    "aerospace",
    "orbital",
    "quantum",
    "bioinformatics",
    "genomic",
    "pharmacology",
    "epidemiology",
    "cybersecurity",
    "penetration test",
    "vulnerability",
    "exploit",
    "forensic",
    "cryptograph",
    "blockchain",
    "smart contract",
    "solidity",
    "defi",
    "semiconductor",
    "vlsi",
    "fpga",
    "asic",
    "signal processing",
    "control theory",
    "fluid dynamics",
    "thermodynamics",
    "topology",
    "category theory",
    "abstract algebra",
    "differential equation",
    "stochastic",
];
